Service:
  name: "things-service"
  path_prefix: ""
  version: "0.0.1"
  debug: false
  port: 8080
#Database:
#  engine: "mysql"
#  host: ""
#  name: "things_bd"
#  port: 3306
#  user: "root"
#  password: "root"
Database:
  engine: "sqlite"
  host: ""
  name: ""
  port: 3306
  user: ""
  password: ""
Cache:
  enabled: false
  addr: "localhost:6379"