CREATE TABLE
IF NOT EXISTS things
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT DEFAULT NULL,
    phone TEXT DEFAULT NULL,
    birth_date DATETIME NOT NULL,
    start_day INTEGER NOT NULL
);